pipeline {
    agent none
    //기본적으로 체크아웃을 하지 않는 옵션
    options { 
        skipDefaultCheckout(true)
        timeout(time: 600, unit: 'SECONDS') 
    }
    stages {
        stage('Checkout repository') {
            agent any
            steps {
                checkout scm
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'node:12.19.0-alpine3.9'
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Docker build') {
            agent any
            steps {
                sh 'docker-compose  -v'
                sh 'docker-compose up -d proxy dev'
            }
        }
    }
}