pipeline {
    agent none
    //기본적으로 체크아웃을 하지 않는 옵션
    options { 
        skipDefaultCheckout(true)
        timeout(time: 1800, unit: 'SECONDS') 
    }
    stages {
        stage('Checkout repository') {
            agent any
            steps {
                checkout scm
            }
        }
        stage('Docker build') {
            agent any
            steps {
                sh 'docker-compose  -v'
                sh 'docker-compose build dev && docker-compose restart dev'
            }
        }
    }
}